In [108]:
import pandas as pd
import numpy as np

In [109]:
df=pd.read_csv("/content/resume_screening_all_selected_columns_encoded.csv", engine='python')

In [110]:
df.head()

,Resume_ID,Name,Age,Gender,Location,Degree,University,Education,Years_Experience,Skills,Certifications,Job_Role_Applied,Required_Skills,Required_Experience,Projects_Count,Match_Score,Expected_Salary,Is_Shortlisted,Application_Status,Recruiter_Decision
0,RES240561,454,34,1,6,3,9,0,0.2,48789,4,9,4,2,7,32.1,20000.0,1,0,0
1,RES162752,127,25,1,2,2,2,0,0.3,38538,4,0,5,3,6,38.2,20000.0,1,0,0
2,RES188621,244,32,1,4,7,9,0,0.5,139894,0,2,8,3,3,43.8,20000.0,1,0,0
3,RES242177,309,24,1,3,5,0,3,0.4,135967,4,1,3,2,6,44.5,20000.0,1,0,0
4,RES132776,709,35,0,5,4,4,0,0.1,93614,4,6,6,4,3,47.2,20000.0,1,0,0

In [111]:
df.isnull().sum()

Resume_ID                 0
Name                      0
Age                       0
Gender                    0
Location                  0
Degree                    0
University                0
Education                 0
Years_Experience          0
Skills                    0
Certifications            0
Job_Role_Applied          0
Required_Skills           0
Required_Experience       0
Projects_Count            0
Match_Score            6012
Expected_Salary        6016
Is_Shortlisted            0
Application_Status        0
Recruiter_Decision        0
dtype: int64

In [112]:
df.nunique()

Resume_ID              200000
Name                      800
Age                        40
Gender                      3
Location                    7
Degree                     10
University                 13
Education                   5
Years_Experience          339
Skills                 149919
Certifications              6
Job_Role_Applied           10
Required_Skills             9
Required_Experience         6
Projects_Count             17
Match_Score               830
Expected_Salary         59447
Is_Shortlisted              2
Application_Status          2
Recruiter_Decision          3
dtype: int64

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200000 entries, 0 to 199999
Data columns (total 20 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   Resume_ID            200000 non-null  object
 1   Name                 200000 non-null  int64
 2   Age                  200000 non-null  int64
 3   Gender               200000 non-null  int64
 4   Location             200000 non-null  int64
 5   Degree               200000 non-null  int64
 6   University           200000 non-null  int64
 7   Education            200000 non-null  int64
 8   Years_Experience     200000 non-null  float64
 9   Skills               200000 non-null  int64
 10  Certifications       200000 non-null  int64
 11  Job_Role_Applied     200000 non-null  int64
 12  Required_Skills      200000 non-null  int64
 13  Required_Experience  200000 non-null  int64
 14  Projects_Count       200000 non-null  int64
 15  Match_Score          193988 non-null  float64
 16  Expected_Salary      193984 non-null  float64
 17  Is_Shortlisted       200000 non-null  int64
 18  Application_Status   200000 non-null  int64
 19  Recruiter_Decision   200000 non-null  int64
dtypes: float64(3), int64(16), object(1)
memory usage: 30.5+ MB

In [114]:
for col in ['Location', 'Degree', 'University', 'Education','Certifications']:
    mode_value = df[col].mode()[0]
    df[col].fillna(mode_value, inplace=True)

/tmp/ipykernel_683/3237665210.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_value, inplace=True)
/tmp/ipykernel_683/3237665210.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_value, inplace=True)
/tmp/ipykernel_683/3237665210.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_value, inplace=True)
/tmp/ipykernel_683/3237665210.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_value, inplace=True)
/tmp/ipykernel_683/3237665210.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_value, inplace=True)

In [115]:
df.isnull().sum()

Resume_ID                 0
Name                      0
Age                       0
Gender                    0
Location                  0
Degree                    0
University                0
Education                 0
Years_Experience          0
Skills                    0
Certifications            0
Job_Role_Applied          0
Required_Skills           0
Required_Experience       0
Projects_Count            0
Match_Score            6012
Expected_Salary        6016
Is_Shortlisted            0
Application_Status        0
Recruiter_Decision        0
dtype: int64

In [116]:
df['Certifications'].shape

(200000,)

In [117]:
df['Age'].unique()

array([34, 25, 32, 24, 35, 41, 26, 22, 20, 37, 30, 33, 39, 28, 27, 21, 29,
       23, 31, 36, 38, 45, 40, 42, 46, 43, 44, 56, 47, 49, 52, 59, 58, 48,
       51, 53, 57, 50, 55, 54])

In [118]:
df['Match_Score'].describe()

count    193988.000000
mean         66.982005
std          14.905031
min           0.000000
25%          56.800000
50%          67.000000
75%          77.200000
max         100.000000
Name: Match_Score, dtype: float64

In [119]:

df['Expected_Salary'].describe()

count    193984.000000
mean      47951.372755
std       18580.296366
min       20000.000000
25%       35299.000000
50%       43125.500000
75%       55574.000000
max      198287.000000
Name: Expected_Salary, dtype: float64

In [120]:
Q1 = df['Expected_Salary'].quantile(0.25)
Q3 = df['Expected_Salary'].quantile(0.75)

In [121]:
IQR=Q3-Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[(df['Expected_Salary'] < lower) | (df['Expected_Salary'] > upper)]

print(outliers)

        Resume_ID  Name  Age  Gender  Location  Degree  University  Education  \
34410   RES112844   344   36       1         1       8           4          0
34413   RES177219   136   34       1         3       2           2          3
34435   RES234117   639   32       1         6       2           2          3
34437   RES202094   241   36       1         6       8          10          1
34439   RES178245   342   22       1         1       0           0          0
...           ...   ...  ...     ...       ...     ...         ...        ...
198932  RES112076   648   26       0         6       0           6          2
198933  RES187592    55   29       1         4       6           3          2
198934  RES278182   577   20       1         6       0          10          0
198935  RES126690   657   23       0         3       9          11          0
198936  RES215095   721   26       0         3       2           2          0

        Years_Experience  Skills  Certifications  Job_Role_Applied  \
34410               14.2   42695               3                 6
34413               12.6   63224               5                 7
34435               14.2  115159               1                 5
34437               12.0   23153               3                 2
34439               10.7   35296               0                 7
...                  ...     ...             ...               ...
198932              35.0   61321               4                 2
198933              35.0  117813               4                 3
198934              35.0   14768               0                 0
198935              35.0   16196               5                 2
198936              35.0   97298               0                 8

        Required_Skills  Required_Experience  Projects_Count  Match_Score  \
34410                 6                    4               6         39.8
34413                 0                    5               4         67.3
34435                 0                    1               2         61.8
34437                 8                    2               9         76.8
34439                 0                    5               5        100.0
...                 ...                  ...             ...          ...
198932                8                    2               7         88.5
198933                2                    3               3         68.8
198934                5                    3               2         89.6
198935                8                    1               3         78.2
198936                1                    2               6         66.3

        Expected_Salary  Is_Shortlisted  Application_Status  \
34410           86050.0               1                   0
34413           86067.0               1                   0
34435           86171.0               1                   0
34437           86173.0               1                   0
34439           86182.0               1                   0
...                 ...             ...                 ...
198932         187754.0               1                   1
198933         188482.0               1                   1
198934         188525.0               1                   1
198935         190366.0               1                   1
198936         191479.0               1                   1

        Recruiter_Decision
34410                    0
34413                    0
34435                    0
34437                    0
34439                    0
...                    ...
198932                   2
198933                   2
198934                   2
198935                   2
198936                   2

[7080 rows x 20 columns]

In [122]:
print(outliers.head())

       Resume_ID  Name  Age  Gender  Location  Degree  University  Education  \
34410  RES112844   344   36       1         1       8           4          0
34413  RES177219   136   34       1         3       2           2          3
34435  RES234117   639   32       1         6       2           2          3
34437  RES202094   241   36       1         6       8          10          1
34439  RES178245   342   22       1         1       0           0          0

       Years_Experience  Skills  Certifications  Job_Role_Applied  \
34410              14.2   42695               3                 6
34413              12.6   63224               5                 7
34435              14.2  115159               1                 5
34437              12.0   23153               3                 2
34439              10.7   35296               0                 7

       Required_Skills  Required_Experience  Projects_Count  Match_Score  \
34410                6                    4               6         39.8
34413                0                    5               4         67.3
34435                0                    1               2         61.8
34437                8                    2               9         76.8
34439                0                    5               5        100.0

       Expected_Salary  Is_Shortlisted  Application_Status  Recruiter_Decision
34410          86050.0               1                   0                   0
34413          86067.0               1                   0                   0
34435          86171.0               1                   0                   0
34437          86173.0               1                   0                   0
34439          86182.0               1                   0                   0

In [123]:
df.isnull().sum()

Resume_ID                 0
Name                      0
Age                       0
Gender                    0
Location                  0
Degree                    0
University                0
Education                 0
Years_Experience          0
Skills                    0
Certifications            0
Job_Role_Applied          0
Required_Skills           0
Required_Experience       0
Projects_Count            0
Match_Score            6012
Expected_Salary        6016
Is_Shortlisted            0
Application_Status        0
Recruiter_Decision        0
dtype: int64

In [124]:
df['Match_Score'].fillna(df['Match_Score'].mean(), inplace=True)

/tmp/ipykernel_683/219404988.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Match_Score'].fillna(df['Match_Score'].mean(), inplace=True)

In [125]:
df['Expected_Salary'].fillna(df['Expected_Salary'].median(),inplace=True)

/tmp/ipykernel_683/2126968350.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Expected_Salary'].fillna(df['Expected_Salary'].median(),inplace=True)

In [126]:
df.isnull().sum()

Resume_ID              0
Name                   0
Age                    0
Gender                 0
Location               0
Degree                 0
University             0
Education              0
Years_Experience       0
Skills                 0
Certifications         0
Job_Role_Applied       0
Required_Skills        0
Required_Experience    0
Projects_Count         0
Match_Score            0
Expected_Salary        0
Is_Shortlisted         0
Application_Status     0
Recruiter_Decision     0
dtype: int64

In [127]:
df['Recruiter_Decision'].unique()

array([0, 1, 2])

In [128]:
df['Application_Status'].unique()

array([0, 1])

In [129]:
outliers=(7080/200000)*100
print(outliers)

3.54

In [130]:
X=df.drop(['Recruiter_Decision'],axis=1)
y=df['Recruiter_Decision']

In [131]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [132]:
df.head()

,Resume_ID,Name,Age,Gender,Location,Degree,University,Education,Years_Experience,Skills,Certifications,Job_Role_Applied,Required_Skills,Required_Experience,Projects_Count,Match_Score,Expected_Salary,Is_Shortlisted,Application_Status,Recruiter_Decision
0,RES240561,454,34,1,6,3,9,0,0.2,48789,4,9,4,2,7,32.1,20000.0,1,0,0
1,RES162752,127,25,1,2,2,2,0,0.3,38538,4,0,5,3,6,38.2,20000.0,1,0,0
2,RES188621,244,32,1,4,7,9,0,0.5,139894,0,2,8,3,3,43.8,20000.0,1,0,0
3,RES242177,309,24,1,3,5,0,3,0.4,135967,4,1,3,2,6,44.5,20000.0,1,0,0
4,RES132776,709,35,0,5,4,4,0,0.1,93614,4,6,6,4,3,47.2,20000.0,1,0,0

In [133]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
cols = df.select_dtypes(include=['object']).columns
for col in cols:
    df[col] = le.fit_transform(df[col].astype(str))

print(df.head())

   Resume_ID  Name  Age  Gender  Location  Degree  University  Education  \
0     140560   454   34       1         6       3           9          0
1      62751   127   25       1         2       2           2          0
2      88620   244   32       1         4       7           9          0
3     142176   309   24       1         3       5           0          3
4      32775   709   35       0         5       4           4          0

   Years_Experience  Skills  Certifications  Job_Role_Applied  \
0               0.2   48789               4                 9
1               0.3   38538               4                 0
2               0.5  139894               0                 2
3               0.4  135967               4                 1
4               0.1   93614               4                 6

   Required_Skills  Required_Experience  Projects_Count  Match_Score  \
0                4                    2               7         32.1
1                5                    3               6         38.2
2                8                    3               3         43.8
3                3                    2               6         44.5
4                6                    4               3         47.2

   Expected_Salary  Is_Shortlisted  Application_Status  Recruiter_Decision
0          20000.0               1                   0                   0
1          20000.0               1                   0                   0
2          20000.0               1                   0                   0
3          20000.0               1                   0                   0
4          20000.0               1                   0                   0

In [134]:
df['Resume_ID']=le.fit_transform(df['Resume_ID'])

In [135]:
df.head()

,Resume_ID,Name,Age,Gender,Location,Degree,University,Education,Years_Experience,Skills,Certifications,Job_Role_Applied,Required_Skills,Required_Experience,Projects_Count,Match_Score,Expected_Salary,Is_Shortlisted,Application_Status,Recruiter_Decision
0,140560,454,34,1,6,3,9,0,0.2,48789,4,9,4,2,7,32.1,20000.0,1,0,0
1,62751,127,25,1,2,2,2,0,0.3,38538,4,0,5,3,6,38.2,20000.0,1,0,0
2,88620,244,32,1,4,7,9,0,0.5,139894,0,2,8,3,3,43.8,20000.0,1,0,0
3,142176,309,24,1,3,5,0,3,0.4,135967,4,1,3,2,6,44.5,20000.0,1,0,0
4,32775,709,35,0,5,4,4,0,0.1,93614,4,6,6,4,3,47.2,20000.0,1,0,0

In [136]:
df['Resume_ID'].unique()

array([140560,  62751,  88620, ..., 167180,  92938, 176072])

In [137]:
df.head()

,Resume_ID,Name,Age,Gender,Location,Degree,University,Education,Years_Experience,Skills,Certifications,Job_Role_Applied,Required_Skills,Required_Experience,Projects_Count,Match_Score,Expected_Salary,Is_Shortlisted,Application_Status,Recruiter_Decision
0,140560,454,34,1,6,3,9,0,0.2,48789,4,9,4,2,7,32.1,20000.0,1,0,0
1,62751,127,25,1,2,2,2,0,0.3,38538,4,0,5,3,6,38.2,20000.0,1,0,0
2,88620,244,32,1,4,7,9,0,0.5,139894,0,2,8,3,3,43.8,20000.0,1,0,0
3,142176,309,24,1,3,5,0,3,0.4,135967,4,1,3,2,6,44.5,20000.0,1,0,0
4,32775,709,35,0,5,4,4,0,0.1,93614,4,6,6,4,3,47.2,20000.0,1,0,0

In [138]:
df['Location'].unique()

array([6, 2, 4, 3, 5, 0, 1])

In [139]:
df['Skills'].unique()

array([ 48789,  38538, 139894, ...,  50926,  44158,  14821])

In [140]:
df['University'].unique()

array([ 9,  2,  0,  4, 10,  8,  1,  3, 11,  6, 12,  5,  7])

In [141]:
df['Degree'].unique()

array([3, 2, 7, 5, 4, 0, 1, 8, 6, 9])

In [142]:


df["Is_Shortlisted"] = df["Is_Shortlisted"].fillna(df["Is_Shortlisted"].mode()[0])

df["Application_Status"] = df["Application_Status"].fillna(df["Application_Status"].mode()[0])

df["Recruiter_Decision"] = df["Recruiter_Decision"].fillna(df["Recruiter_Decision"].mode()[0])

In [143]:
df.isnull().sum()

Resume_ID              0
Name                   0
Age                    0
Gender                 0
Location               0
Degree                 0
University             0
Education              0
Years_Experience       0
Skills                 0
Certifications         0
Job_Role_Applied       0
Required_Skills        0
Required_Experience    0
Projects_Count         0
Match_Score            0
Expected_Salary        0
Is_Shortlisted         0
Application_Status     0
Recruiter_Decision     0
dtype: int64

In [144]:
!pip install catboost

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)

In [145]:
from catboost import CatBoostClassifier

In [146]:
X = df.drop(["Application_Status", "Gender", "Resume_ID", "Name"], axis=1)
y = df["Gender"]

In [147]:
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = CatBoostClassifier(iterations=500, learning_rate=0.1, depth=6, loss_function="MultiClass", random_seed=42, verbose=100)

In [148]:
model.fit(X_train, y_train)

0:	learn: 1.0517981	total: 60.3ms	remaining: 30.1s
100:	learn: 0.7530115	total: 9.7s	remaining: 38.3s
200:	learn: 0.7479539	total: 17s	remaining: 25.3s
300:	learn: 0.7434079	total: 21.9s	remaining: 14.5s
400:	learn: 0.7391208	total: 27.5s	remaining: 6.78s
499:	learn: 0.7347981	total: 32.4s	remaining: 0us

CatBoostClassifier(depth=6, iterations=500, learning_rate=0.1, loss_function='MultiClass', random_seed=42, verbose=100)

In [149]:
model.fit(X_train, y_train)

0:	learn: 1.0517981	total: 56.5ms	remaining: 28.2s
100:	learn: 0.7530115	total: 7.98s	remaining: 31.5s
200:	learn: 0.7479539	total: 16.4s	remaining: 24.3s
300:	learn: 0.7434079	total: 21.6s	remaining: 14.3s
400:	learn: 0.7391208	total: 26.5s	remaining: 6.54s
499:	learn: 0.7347981	total: 32s	remaining: 0us

CatBoostClassifier(depth=6, iterations=500, learning_rate=0.1, loss_function='MultiClass', random_seed=42, verbose=100)

In [150]:
model.score(X_train, y_train)

np.float64(0.5981375)

In [151]:
model.score(X_test, y_test)

np.float64(0.556525)

In [152]:
print(df.duplicated().sum())

df = df.drop_duplicates()

0

In [153]:
df.isnull().sum()

Resume_ID              0
Name                   0
Age                    0
Gender                 0
Location               0
Degree                 0
University             0
Education              0
Years_Experience       0
Skills                 0
Certifications         0
Job_Role_Applied       0
Required_Skills        0
Required_Experience    0
Projects_Count         0
Match_Score            0
Expected_Salary        0
Is_Shortlisted         0
Application_Status     0
Recruiter_Decision     0
dtype: int64

In [154]:
importance = model.get_feature_importance()

feature_importance = (
    pd.DataFrame({
        "Feature": X_train.columns,
        "Importance": importance
    })
    .sort_values("Importance", ascending=False)
)

print(feature_importance.head(20))

                Feature  Importance
6                Skills   10.992657
12          Match_Score   10.617738
13      Expected_Salary    8.524678
0                   Age    7.456134
5      Years_Experience    7.422680
3            University    6.837787
2                Degree    6.374525
11       Projects_Count    6.299700
14       Is_Shortlisted    6.047117
1              Location    5.749063
8      Job_Role_Applied    5.187447
7        Certifications    4.804120
10  Required_Experience    4.070127
9       Required_Skills    3.700303
15   Recruiter_Decision    3.041332
4             Education    2.874594

In [155]:
df.head()

,Resume_ID,Name,Age,Gender,Location,Degree,University,Education,Years_Experience,Skills,Certifications,Job_Role_Applied,Required_Skills,Required_Experience,Projects_Count,Match_Score,Expected_Salary,Is_Shortlisted,Application_Status,Recruiter_Decision
0,140560,454,34,1,6,3,9,0,0.2,48789,4,9,4,2,7,32.1,20000.0,1,0,0
1,62751,127,25,1,2,2,2,0,0.3,38538,4,0,5,3,6,38.2,20000.0,1,0,0
2,88620,244,32,1,4,7,9,0,0.5,139894,0,2,8,3,3,43.8,20000.0,1,0,0
3,142176,309,24,1,3,5,0,3,0.4,135967,4,1,3,2,6,44.5,20000.0,1,0,0
4,32775,709,35,0,5,4,4,0,0.1,93614,4,6,6,4,3,47.2,20000.0,1,0,0

In [156]:
df = df.drop('Recruiter_Decision', axis=1)

In [158]:
df.head()

,Resume_ID,Name,Age,Gender,Location,Degree,University,Education,Years_Experience,Skills,Certifications,Job_Role_Applied,Required_Skills,Required_Experience,Projects_Count,Match_Score,Expected_Salary,Is_Shortlisted,Application_Status
0,140560,454,34,1,6,3,9,0,0.2,48789,4,9,4,2,7,32.1,20000.0,1,0
1,62751,127,25,1,2,2,2,0,0.3,38538,4,0,5,3,6,38.2,20000.0,1,0
2,88620,244,32,1,4,7,9,0,0.5,139894,0,2,8,3,3,43.8,20000.0,1,0
3,142176,309,24,1,3,5,0,3,0.4,135967,4,1,3,2,6,44.5,20000.0,1,0
4,32775,709,35,0,5,4,4,0,0.1,93614,4,6,6,4,3,47.2,20000.0,1,0

In [159]:
from sklearn.model_selection import train_test_split

# Features and Target
X = df.drop("Is_Shortlisted", axis=1)
y = df["Is_Shortlisted"]

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train shape:", X_train.shape)
print("X_test shape :", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape :", y_test.shape)

X_train shape: (160000, 18)
X_test shape : (40000, 18)
y_train shape: (160000,)
y_test shape : (40000,)

In [160]:
from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=True, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=500, n_jobs=None,
              num_parallel_tree=None, ...)

In [163]:
model.score(X_train, y_train)

0.82453125

In [162]:
model.score(X_test,y_test)

0.816475

In [170]:
import pandas as pd

new_candidate = pd.DataFrame({
    "Resume_ID": [0], # Placeholder value
    "Name": [0],      # Placeholder value
    "Age": [30],
    "Gender": [1],    # Placeholder value (e.g., 0 for female, 1 for male, 2 for other)
    "Location": [1],
    "Degree": [2],
    "University": [5],
    "Education": [1],
    "Years_Experience": [3],
    "Skills": [10],
    "Certifications": [2],
    "Job_Role_Applied": [2],
    "Required_Skills": [8],
    "Required_Experience": [2],
    "Projects_Count": [5],
    "Match_Score": [85],
    "Expected_Salary": [600000],
    "Application_Status": [0] # Placeholder value (e.g., 0 for submitted, 1 for in progress)
})

prediction = model.predict(new_candidate)

if prediction[0] == 1:
    print("✅ Candidate is Shortlisted")
else:
    print("❌ Candidate is Not Shortlisted")

✅ Candidate is Shortlisted