In [18]:
import pandas as pd
import numpy as np

In [19]:
df=pd.read_csv('/content/resume_screening_same_columns_label_encoded.csv',engine='python')

### Data Loading Issue

It appears the CSV file specified in the previous cell was not found. Please upload the file `resume_screening_all_selected_columns_encoded.csv` to the `/content/` directory in your Colab environment.

If you'd like to proceed with a dummy dataset to test the remaining code structure, run the following cell. Otherwise, upload the file and re-run cell `Z8zyOF493j-m`.

In [20]:
# This cell creates a dummy DataFrame to allow subsequent code to run without FileNotFoundError or NameError for 'df'.
# Please replace this with your actual data loading once the CSV file is available.

data = {
    'Resume_ID': range(100),
    'Name': [f'Applicant_{i}' for i in range(100)],
    'Location': np.random.choice(['New York', 'Los Angeles', 'Chicago', 'Houston'], 100),
    'Skills': np.random.choice(['Python', 'SQL', 'Java', 'Data Science', 'Machine Learning'], 100),
    'Degree': np.random.choice(['B.S.', 'M.S.', 'Ph.D.'], 100),
    'University': np.random.choice(['State Uni', 'Tech Uni', 'Global Uni'], 100),
    'Education': np.random.choice(['High School', 'Bachelors', 'Masters', 'Doctorate'], 100),
    'Certifications': np.random.choice(['PMP', 'CSM', 'AWS', 'None'], 100),
    'Age': np.random.randint(22, 45, 100),
    'Match_Score': np.random.uniform(0.5, 0.99, 100),
    'Expected_Salary': np.random.randint(50000, 150000, 100),
    'Is_Shortlisted': np.random.choice([0, 1], 100),
    'Application_Status': np.random.choice(['Pending', 'Accepted', 'Rejected'], 100),
    'Recruiter_Decision': np.random.choice(['Hire', 'Reject'], 100),
    'Gender': np.random.choice(['Male', 'Female'], 100)
}

df = pd.DataFrame(data)

display(df.head())

,Resume_ID,Name,Location,Skills,Degree,University,Education,Certifications,Age,Match_Score,Expected_Salary,Is_Shortlisted,Application_Status,Recruiter_Decision,Gender
0,0,Applicant_0,Chicago,SQL,M.S.,Global Uni,Masters,AWS,23,0.951192,99596,0,Accepted,Hire,Male
1,1,Applicant_1,Chicago,Machine Learning,Ph.D.,Tech Uni,Doctorate,None,44,0.938469,107865,1,Accepted,Reject,Female
2,2,Applicant_2,New York,SQL,B.S.,Tech Uni,Doctorate,None,29,0.829559,58651,1,Rejected,Reject,Female
3,3,Applicant_3,Chicago,Data Science,M.S.,State Uni,Doctorate,None,35,0.808133,65032,1,Accepted,Reject,Male
4,4,Applicant_4,New York,Java,Ph.D.,State Uni,Masters,AWS,32,0.544850,84199,1,Accepted,Hire,Female

In [21]:
df.head()

,Resume_ID,Name,Location,Skills,Degree,University,Education,Certifications,Age,Match_Score,Expected_Salary,Is_Shortlisted,Application_Status,Recruiter_Decision,Gender
0,0,Applicant_0,Chicago,SQL,M.S.,Global Uni,Masters,AWS,23,0.951192,99596,0,Accepted,Hire,Male
1,1,Applicant_1,Chicago,Machine Learning,Ph.D.,Tech Uni,Doctorate,None,44,0.938469,107865,1,Accepted,Reject,Female
2,2,Applicant_2,New York,SQL,B.S.,Tech Uni,Doctorate,None,29,0.829559,58651,1,Rejected,Reject,Female
3,3,Applicant_3,Chicago,Data Science,M.S.,State Uni,Doctorate,None,35,0.808133,65032,1,Accepted,Reject,Male
4,4,Applicant_4,New York,Java,Ph.D.,State Uni,Masters,AWS,32,0.544850,84199,1,Accepted,Hire,Female

In [22]:
df.isnull().sum()

Resume_ID             0
Name                  0
Location              0
Skills                0
Degree                0
University            0
Education             0
Certifications        0
Age                   0
Match_Score           0
Expected_Salary       0
Is_Shortlisted        0
Application_Status    0
Recruiter_Decision    0
Gender                0
dtype: int64

In [23]:
df.nunique()

Resume_ID             100
Name                  100
Location                4
Skills                  5
Degree                  3
University              3
Education               4
Certifications          4
Age                    23
Match_Score           100
Expected_Salary       100
Is_Shortlisted          2
Application_Status      3
Recruiter_Decision      2
Gender                  2
dtype: int64

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Resume_ID           100 non-null    int64
 1   Name                100 non-null    object
 2   Location            100 non-null    object
 3   Skills              100 non-null    object
 4   Degree              100 non-null    object
 5   University          100 non-null    object
 6   Education           100 non-null    object
 7   Certifications      100 non-null    object
 8   Age                 100 non-null    int64
 9   Match_Score         100 non-null    float64
 10  Expected_Salary     100 non-null    int64
 11  Is_Shortlisted      100 non-null    int64
 12  Application_Status  100 non-null    object
 13  Recruiter_Decision  100 non-null    object
 14  Gender              100 non-null    object
dtypes: float64(1), int64(4), object(10)
memory usage: 11.8+ KB

In [25]:
for col in ['Location', 'Degree', 'University', 'Education','Certifications']:
    mode_value = df[col].mode()[0]
    df[col].fillna(mode_value, inplace=True)

/tmp/ipykernel_492/3237665210.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_value, inplace=True)

In [26]:
df.isnull().sum()

Resume_ID             0
Name                  0
Location              0
Skills                0
Degree                0
University            0
Education             0
Certifications        0
Age                   0
Match_Score           0
Expected_Salary       0
Is_Shortlisted        0
Application_Status    0
Recruiter_Decision    0
Gender                0
dtype: int64

In [27]:
df['Certifications'].shape

(100,)

In [28]:
df['Age'].unique()

array([23, 44, 29, 35, 32, 41, 38, 39, 28, 34, 42, 33, 43, 26, 25, 24, 36,
       22, 27, 30, 31, 37, 40])

In [29]:
df['Match_Score'].describe()

count    100.000000
mean       0.762745
std        0.132401
min        0.507162
25%        0.669555
50%        0.742788
75%        0.875849
max        0.986330
Name: Match_Score, dtype: float64

In [30]:

df['Expected_Salary'].describe()

count       100.000000
mean     104229.110000
std       31772.842544
min       51710.000000
25%       74351.000000
50%      107684.500000
75%      133063.000000
max      148880.000000
Name: Expected_Salary, dtype: float64

In [31]:
Q1 = df['Expected_Salary'].quantile(0.25)
Q3 = df['Expected_Salary'].quantile(0.75)

In [32]:
IQR=Q3-Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[(df['Expected_Salary'] < lower) | (df['Expected_Salary'] > upper)]

print(outliers)

Empty DataFrame
Columns: [Resume_ID, Name, Location, Skills, Degree, University, Education, Certifications, Age, Match_Score, Expected_Salary, Is_Shortlisted, Application_Status, Recruiter_Decision, Gender]
Index: []

In [33]:
print(outliers.head())

Empty DataFrame
Columns: [Resume_ID, Name, Location, Skills, Degree, University, Education, Certifications, Age, Match_Score, Expected_Salary, Is_Shortlisted, Application_Status, Recruiter_Decision, Gender]
Index: []

In [34]:
df.isnull().sum()

Resume_ID             0
Name                  0
Location              0
Skills                0
Degree                0
University            0
Education             0
Certifications        0
Age                   0
Match_Score           0
Expected_Salary       0
Is_Shortlisted        0
Application_Status    0
Recruiter_Decision    0
Gender                0
dtype: int64

In [35]:
df['Match_Score'].fillna(df['Match_Score'].mean(), inplace=True)

/tmp/ipykernel_492/219404988.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Match_Score'].fillna(df['Match_Score'].mean(), inplace=True)

In [36]:
df['Expected_Salary'].fillna(df['Expected_Salary'].median(),inplace=True)

/tmp/ipykernel_492/2126968350.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Expected_Salary'].fillna(df['Expected_Salary'].median(),inplace=True)

In [37]:
df.isnull().sum()

Resume_ID             0
Name                  0
Location              0
Skills                0
Degree                0
University            0
Education             0
Certifications        0
Age                   0
Match_Score           0
Expected_Salary       0
Is_Shortlisted        0
Application_Status    0
Recruiter_Decision    0
Gender                0
dtype: int64

In [38]:
df['Recruiter_Decision'].unique()

array(['Hire', 'Reject'], dtype=object)

In [39]:
df['Application_Status'].unique()

array(['Accepted', 'Rejected', 'Pending'], dtype=object)

In [40]:
outliers=(7080/200000)*100
print(outliers)

3.54

In [41]:
X=df.drop(['Recruiter_Decision'],axis=1)
y=df['Recruiter_Decision']

In [42]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [43]:
df.head()

,Resume_ID,Name,Location,Skills,Degree,University,Education,Certifications,Age,Match_Score,Expected_Salary,Is_Shortlisted,Application_Status,Recruiter_Decision,Gender
0,0,Applicant_0,Chicago,SQL,M.S.,Global Uni,Masters,AWS,23,0.951192,99596,0,Accepted,Hire,Male
1,1,Applicant_1,Chicago,Machine Learning,Ph.D.,Tech Uni,Doctorate,None,44,0.938469,107865,1,Accepted,Reject,Female
2,2,Applicant_2,New York,SQL,B.S.,Tech Uni,Doctorate,None,29,0.829559,58651,1,Rejected,Reject,Female
3,3,Applicant_3,Chicago,Data Science,M.S.,State Uni,Doctorate,None,35,0.808133,65032,1,Accepted,Reject,Male
4,4,Applicant_4,New York,Java,Ph.D.,State Uni,Masters,AWS,32,0.544850,84199,1,Accepted,Hire,Female

In [44]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
cols = df.select_dtypes(include=['object']).columns
for col in cols:
    df[col] = le.fit_transform(df[col].astype(str))

print(df.head())

   Resume_ID  Name  Location  Skills  Degree  University  Education  \
0          0     0         0       4       1           0          3
1          1     1         0       2       2           2          1
2          2    12         3       4       0           2          1
3          3    23         0       0       1           1          1
4          4    34         3       1       2           1          3

   Certifications  Age  Match_Score  Expected_Salary  Is_Shortlisted  \
0               0   23     0.951192            99596               0
1               2   44     0.938469           107865               1
2               2   29     0.829559            58651               1
3               2   35     0.808133            65032               1
4               0   32     0.544850            84199               1

   Application_Status  Recruiter_Decision  Gender
0                   0                   0       1
1                   0                   1       0
2                   2                   1       0
3                   0                   1       1
4                   0                   0       0

In [45]:
df['Resume_ID']=le.fit_transform(df['Resume_ID'])

In [46]:
df.head()

,Resume_ID,Name,Location,Skills,Degree,University,Education,Certifications,Age,Match_Score,Expected_Salary,Is_Shortlisted,Application_Status,Recruiter_Decision,Gender
0,0,0,0,4,1,0,3,0,23,0.951192,99596,0,0,0,1
1,1,1,0,2,2,2,1,2,44,0.938469,107865,1,0,1,0
2,2,12,3,4,0,2,1,2,29,0.829559,58651,1,2,1,0
3,3,23,0,0,1,1,1,2,35,0.808133,65032,1,0,1,1
4,4,34,3,1,2,1,3,0,32,0.544850,84199,1,0,0,0

In [47]:
df['Resume_ID'].unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [48]:
df.head()

,Resume_ID,Name,Location,Skills,Degree,University,Education,Certifications,Age,Match_Score,Expected_Salary,Is_Shortlisted,Application_Status,Recruiter_Decision,Gender
0,0,0,0,4,1,0,3,0,23,0.951192,99596,0,0,0,1
1,1,1,0,2,2,2,1,2,44,0.938469,107865,1,0,1,0
2,2,12,3,4,0,2,1,2,29,0.829559,58651,1,2,1,0
3,3,23,0,0,1,1,1,2,35,0.808133,65032,1,0,1,1
4,4,34,3,1,2,1,3,0,32,0.544850,84199,1,0,0,0

In [49]:
df['Location'].unique()

array([0, 3, 2, 1])

In [50]:
df['Skills'].unique()

array([4, 2, 0, 1, 3])

In [51]:
df['University'].unique()

array([0, 2, 1])

In [52]:
df['Degree'].unique()

array([1, 2, 0])

In [53]:


df["Is_Shortlisted"] = df["Is_Shortlisted"].fillna(df["Is_Shortlisted"].mode()[0])

df["Application_Status"] = df["Application_Status"].fillna(df["Application_Status"].mode()[0])

df["Recruiter_Decision"] = df["Recruiter_Decision"].fillna(df["Recruiter_Decision"].mode()[0])

In [54]:
df.isnull().sum()

Resume_ID             0
Name                  0
Location              0
Skills                0
Degree                0
University            0
Education             0
Certifications        0
Age                   0
Match_Score           0
Expected_Salary       0
Is_Shortlisted        0
Application_Status    0
Recruiter_Decision    0
Gender                0
dtype: int64

In [55]:
!pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)
Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl (97.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.1/97.1 MB 11.5 MB/s eta 0:00:00
Installing collected packages: catboost
Successfully installed catboost-1.2.10

In [56]:
from catboost import CatBoostClassifier

In [79]:
X = df.drop(["Is_Shortlisted", "Application_Status", "Gender", "Resume_ID", "Name"], axis=1)
y = df["Is_Shortlisted"]

In [80]:
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Changed loss_function to 'Logloss' for binary classification
model = CatBoostClassifier(iterations=500, learning_rate=0.1, depth=6, loss_function="Logloss", random_seed=42, verbose=100)

In [59]:
model.fit(X_train, y_train)

0:	learn: 0.6753643	total: 46.8ms	remaining: 23.4s
100:	learn: 0.1587819	total: 97.2ms	remaining: 384ms
200:	learn: 0.0719359	total: 150ms	remaining: 224ms
300:	learn: 0.0441810	total: 204ms	remaining: 135ms
400:	learn: 0.0311560	total: 260ms	remaining: 64.2ms
499:	learn: 0.0239905	total: 312ms	remaining: 0us

CatBoostClassifier(depth=6, iterations=500, learning_rate=0.1, loss_function='MultiClass', random_seed=42, verbose=100)

In [60]:
model.fit(X_train, y_train)

0:	learn: 0.6753643	total: 677us	remaining: 338ms
100:	learn: 0.1587819	total: 53.1ms	remaining: 210ms
200:	learn: 0.0719359	total: 106ms	remaining: 158ms
300:	learn: 0.0441810	total: 158ms	remaining: 104ms
400:	learn: 0.0311560	total: 215ms	remaining: 53ms
499:	learn: 0.0239905	total: 266ms	remaining: 0us

CatBoostClassifier(depth=6, iterations=500, learning_rate=0.1, loss_function='MultiClass', random_seed=42, verbose=100)

In [61]:
model.score(X_train, y_train)

np.float64(1.0)

In [62]:
model.score(X_test, y_test)

np.float64(0.6)

In [63]:
print(df.duplicated().sum())

df = df.drop_duplicates()

0

In [64]:
df.isnull().sum()

Resume_ID             0
Name                  0
Location              0
Skills                0
Degree                0
University            0
Education             0
Certifications        0
Age                   0
Match_Score           0
Expected_Salary       0
Is_Shortlisted        0
Application_Status    0
Recruiter_Decision    0
Gender                0
dtype: int64

In [65]:
importance = model.get_feature_importance()

feature_importance = (
    pd.DataFrame({
        "Feature": X_train.columns,
        "Importance": importance
    })
    .sort_values("Importance", ascending=False)
)

print(feature_importance.head(20))

               Feature  Importance
7          Match_Score   19.012813
8      Expected_Salary   14.060748
5       Certifications   10.819233
4            Education   10.152028
3           University   10.081772
6                  Age   10.063068
2               Degree    8.087857
0             Location    5.102587
1               Skills    5.009112
9       Is_Shortlisted    4.142266
10  Recruiter_Decision    3.468516

In [66]:
df.head()

,Resume_ID,Name,Location,Skills,Degree,University,Education,Certifications,Age,Match_Score,Expected_Salary,Is_Shortlisted,Application_Status,Recruiter_Decision,Gender
0,0,0,0,4,1,0,3,0,23,0.951192,99596,0,0,0,1
1,1,1,0,2,2,2,1,2,44,0.938469,107865,1,0,1,0
2,2,12,3,4,0,2,1,2,29,0.829559,58651,1,2,1,0
3,3,23,0,0,1,1,1,2,35,0.808133,65032,1,0,1,1
4,4,34,3,1,2,1,3,0,32,0.544850,84199,1,0,0,0

In [77]:
X=df.drop('Is_Shortlisted',axis=1)

y=df['Is_Shortlisted']

In [83]:
# User input for Recruiter's Decision (for display alongside model's prediction)
# This value will NOT be used as a feature for the CatBoost model prediction.
user_recruiter_decision_input = input("Please enter the Recruiter's Decision for the new candidate (e.g., 'Hire', 'Reject'): ")

# You can also manually set it like this for testing:
# user_recruiter_decision_input = 'Hire'

print(f"User entered Recruiter's Decision: '{user_recruiter_decision_input}'")

KeyboardInterrupt: Interrupted by user

In [89]:
import pandas as pd

# Check if user_recruiter_decision_input is defined, otherwise set a default
# (This is a temporary measure to prevent NameError if cell 89325a0d is not run)
if 'user_recruiter_decision_input' not in globals():
    print("Warning: 'user_recruiter_decision_input' not defined. Using a default value 'Unknown'. Please run cell 89325a0d first.")
    user_recruiter_decision_input = 'Unknown'

# The current 'model' in the kernel was trained with the following features
# (based on the state after cell 'zIWje8cseH-2' and before the intended fix in 'OQZygPhTvvBU' was deleted):
# Location, Skills, Degree, University, Education, Certifications, Age, Match_Score, Expected_Salary, Recruiter_Decision

# Define the new candidate data using string values for categorical features
# We will use the 'encoders' from the kernel state to convert them to numerical values
# The 'Recruiter_Decision' is included here because the current 'model' expects it as a feature.
# This value comes from the user input in cell '89325a0d'.
new_candidate_data_input = {
    "Location": "Los Angeles",
    "Skills": "Java",
    "Degree": "Ph.D.",
    "University": "State Uni",
    "Education": "Masters",
    "Certifications": "PMP",
    "Age": 25,
    "Match_Score": 0.85,
    "Expected_Salary": 80000,

}


# Define the expected order of features that the current model was trained with.
# This order is inferred from the `X` definition in cell `zIWje8cseH-2` and the `feature_importance`.
expected_model_features = [
    "Location", "Skills", "Degree", "University", "Education", "Certifications",
    "Age", "Match_Score", "Expected_Salary", "Recruiter_Decision"
]

# Identify categorical features from the expected list that need encoding
# `categorical_cols` is available from the kernel state.
# Ensure 'encoders' is also available from the kernel state for transformation.
if 'encoders' in globals():
    categorical_features_in_X = [col for col in expected_model_features if col in categorical_cols]

    for col in categorical_features_in_X:
        if col in new_candidate_df.columns:
            try:
                new_candidate_df[col] = encoders[col].transform(new_candidate_df[col].astype(str))
            except ValueError:
                # Handle unseen categories during prediction. Assign a default value (e.g., 0).
                # A more robust solution might involve adding a new category to the encoder
                # or using one-hot encoding if unseen categories are common.
                print(f"Warning: Unseen category for column '{col}' encountered during prediction. Setting to a default encoded value (0).")
                new_candidate_df[col] = 0
else:
    print("Warning: 'encoders' object not found. Categorical features in new_candidate_df might not be correctly encoded.")

# Ensure column order matches the model's training data
new_candidate_df = new_candidate_df[expected_model_features]

prediction = model.predict(new_candidate_df)

print(f"Recruiter's Decision (user input): '{user_recruiter_decision_input}'")
if prediction[0] == 1:
    print("✅ Model Prediction: Candidate is Shortlisted")
else:
    print("❌ Model Prediction: Candidate is Not Shortlisted")

Warning: Unseen category for column 'Location' encountered during prediction. Setting to a default encoded value (0).
Warning: Unseen category for column 'Skills' encountered during prediction. Setting to a default encoded value (0).
Warning: Unseen category for column 'Degree' encountered during prediction. Setting to a default encoded value (0).
Warning: Unseen category for column 'University' encountered during prediction. Setting to a default encoded value (0).
Warning: Unseen category for column 'Education' encountered during prediction. Setting to a default encoded value (0).
Warning: Unseen category for column 'Certifications' encountered during prediction. Setting to a default encoded value (0).

KeyError: "['Recruiter_Decision'] not in index"

In [90]:
import pandas as pd
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
from sklearn.preprocessing import LabelEncoder

# Make a copy of df to avoid modifying the global df for this specific operation
df_processed_new = df.copy()

# Store LabelEncoders to use for new_candidate later
encoders_new = {}
categorical_cols_new = df_processed_new.select_dtypes(include=['object']).columns.tolist()

for col in categorical_cols_new:
    # Only encode if the column is not 'Recruiter_Decision' (if it's being dropped from X later)
    # and if it was present in the original categorical columns.
    if col != 'Recruiter_Decision': # Ensure we don't encode a column that will be dropped before X creation
        le = LabelEncoder()
        df_processed_new[col] = le.fit_transform(df_processed_new[col].astype(str))
        encoders_new[col] = le # Save the fitted encoder
    else:
        # For 'Recruiter_Decision', we will not encode it as it's being removed from features.
        pass

# 1. Redefine X and y to ensure 'Is_Shortlisted' is NOT in X
# Drop 'Application_Status', 'Gender', 'Resume_ID', 'Name' and 'Recruiter_Decision'
X_new = df_processed_new.drop(["Is_Shortlisted", "Application_Status", "Gender", "Resume_ID", "Name", "Recruiter_Decision"], axis=1)
y_new = df_processed_new["Is_Shortlisted"]

# Identify indices of categorical features in X_new for CatBoost
# These must be columns present in X_new, and also were originally categorical
cat_features_indices_new = [
    X_new.columns.get_loc(col) for col in ["Location", "Skills", "Degree", "University", "Education", "Certifications"]
    if col in X_new.columns
]

# 2. Re-initialize CatBoostClassifier and split data
X_train_new, X_test_new, y_train_new, y_test_new = train_test_split(X_new, y_new, test_size=0.2, random_state=42)
model_new = CatBoostClassifier(
    iterations=500,
    learning_rate=0.1,
    depth=6,
    loss_function="Logloss", # Ensure Logloss for binary classification
    random_seed=42,
    verbose=0, # Suppress verbose output
    cat_features=cat_features_indices_new # Tell CatBoost which features are categorical
)

# 3. Re-train the model with the correct X_train_new and y_train_new
model_new.fit(X_train_new, y_train_new)

print("Model retrained successfully without 'Recruiter_Decision' as a feature.")

Model retrained successfully without 'Recruiter_Decision' as a feature.

In [93]:
import pandas as pd

# Check if user_recruiter_decision_input is defined, otherwise set a default
if 'user_recruiter_decision_input' not in globals():
    print("Warning: 'user_recruiter_decision_input' not defined. Using a default value 'Unknown'. Please run cell 89325a0d first.")
    user_recruiter_decision_input = 'Unknown'

# Prepare the new_candidate DataFrame, using string values for categorical features.
# 'Recruiter_Decision' is explicitly excluded from here as it's now a separate user input and not a model feature.
new_candidate_data_input_updated = {
    "Location": "Los Angeles",
    "Skills": "pythom",
    "Degree": "Ph.D.",
    "University": "State Uni",
    "Education": "Masters",
    "Certifications": "PMP",
    "Age": 30,
    "Match_Score": 0.70,
    "Expected_Salary": 10000,
}

new_candidate_df_updated = pd.DataFrame([new_candidate_data_input_updated])

# Ensure 'encoders_new' and 'categorical_cols_new' are available from the newly generated model training cell.
if 'encoders_new' in globals() and 'categorical_cols_new' in globals():
    # Only encode columns that were used as features in the new model
    features_for_encoding = [col for col in X_train_new.columns if col in encoders_new and col in categorical_cols_new]

    for col in features_for_encoding:
        if col in new_candidate_df_updated.columns:
            try:
                new_candidate_df_updated[col] = encoders_new[col].transform(new_candidate_df_updated[col].astype(str))
            except ValueError:
                print(f"Warning: Unseen category for column '{col}' encountered during prediction. Setting to a default encoded value (0).")
                new_candidate_df_updated[col] = 0
else:
    print("Warning: 'encoders_new' or 'categorical_cols_new' not found. Categorical features might not be correctly encoded.")

# Ensure column order matches the newly trained model's training data
new_candidate_df_updated = new_candidate_df_updated[X_train_new.columns]

# Use the newly trained model for prediction
prediction_new = model_new.predict(new_candidate_df_updated)

print(f"Recruiter's Decision (user input): '{user_recruiter_decision_input}'")
if prediction_new[0] == 1:
    print("✅ Model Prediction: Candidate is Shortlisted")
else:
    print("❌ Model Prediction: Candidate is Not Shortlisted")

Warning: Unseen category for column 'Skills' encountered during prediction. Setting to a default encoded value (0).
Recruiter's Decision (user input): 'Unknown'
✅ Model Prediction: Candidate is Shortlisted

In [86]:
import pickle

pickle.dump(model, open("house_price_model.pkl", "wb"))