In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("/content/diabetic_data.csv", engine='python', on_bad_lines='skip')

In [3]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [4]:
df.tail()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
27788,91073484,54889515,Caucasian,Male,[60-70),?,2,1,1,11,...,No,Steady,No,No,No,No,No,Ch,Yes,>30
27789,91074294,900603,Caucasian,Female,[40-50),?,1,1,7,7,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
27790,91077828,109470600,Caucasian,Female,[30-40),?,6,2,7,10,...,No,Up,No,No,No,No,No,Ch,Yes,>30
27791,91077942,89626239,Caucasian,Female,[80-90),?,2,3,1,12,...,No,No,No,No,No,No,No,No,No,>30
27792,91079766,81684747,Caucasian,Female,[60-70),?,1,1,7,1,...,None,None,None,None,None,None,None,None,None,None

In [5]:
df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          1
number_diagnoses                1
max_glu_serum               24633
A1Cresult                   22821
metformin                       1
repaglinide                     1
nateglinide                     1
chlorpropamide                  1
glimepiride                     1
acetohexamide                   1
glipizide                       1
glyburide                       1
tolbutamide                     1
pioglitazone                    1
rosiglitazone                   1
acarbose                        1
miglitol                        1
troglitazone                    1
tolazamide                      1
examide                         1
citoglipton                     1
insulin                         1
glyburide-metformin             1
glipizide-metformin             1
glimepiride-pioglitazone        1
metformin-rosiglitazone         1
metformin-pioglitazone          1
change                          1
diabetesMed                     1
readmitted                      1
dtype: int64

In [6]:
df.drop(['max_glu_serum','A1Cresult'],axis=1,inplace=True)

In [7]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27793 entries, 0 to 27792
Data columns (total 48 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   encounter_id              27793 non-null  int64
 1   patient_nbr               27793 non-null  int64
 2   race                      27793 non-null  object
 3   gender                    27793 non-null  object
 4   age                       27793 non-null  object
 5   weight                    27793 non-null  object
 6   admission_type_id         27793 non-null  int64
 7   discharge_disposition_id  27793 non-null  int64
 8   admission_source_id       27793 non-null  int64
 9   time_in_hospital          27793 non-null  int64
 10  payer_code                27793 non-null  object
 11  medical_specialty         27793 non-null  object
 12  num_lab_procedures        27793 non-null  int64
 13  num_procedures            27793 non-null  int64
 14  num_medications           27793 non-null  int64
 15  number_outpatient         27793 non-null  int64
 16  number_emergency          27793 non-null  int64
 17  number_inpatient          27793 non-null  int64
 18  diag_1                    27793 non-null  object
 19  diag_2                    27793 non-null  object
 20  diag_3                    27792 non-null  object
 21  number_diagnoses          27792 non-null  float64
 22  metformin                 27792 non-null  object
 23  repaglinide               27792 non-null  object
 24  nateglinide               27792 non-null  object
 25  chlorpropamide            27792 non-null  object
 26  glimepiride               27792 non-null  object
 27  acetohexamide             27792 non-null  object
 28  glipizide                 27792 non-null  object
 29  glyburide                 27792 non-null  object
 30  tolbutamide               27792 non-null  object
 31  pioglitazone              27792 non-null  object
 32  rosiglitazone             27792 non-null  object
 33  acarbose                  27792 non-null  object
 34  miglitol                  27792 non-null  object
 35  troglitazone              27792 non-null  object
 36  tolazamide                27792 non-null  object
 37  examide                   27792 non-null  object
 38  citoglipton               27792 non-null  object
 39  insulin                   27792 non-null  object
 40  glyburide-metformin       27792 non-null  object
 41  glipizide-metformin       27792 non-null  object
 42  glimepiride-pioglitazone  27792 non-null  object
 43  metformin-rosiglitazone   27792 non-null  object
 44  metformin-pioglitazone    27792 non-null  object
 45  change                    27792 non-null  object
 46  diabetesMed               27792 non-null  object
 47  readmitted                27792 non-null  object
dtypes: float64(1), int64(12), object(35)
memory usage: 10.2+ MB

In [9]:
df['diag_3'].fillna(df['diag_3'].mode()[0], inplace=True)

/tmp/ipykernel_451/643291854.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['diag_3'].fillna(df['diag_3'].mode()[0], inplace=True)

In [10]:
df.isnull().sum()

encounter_id                0
patient_nbr                 0
race                        0
gender                      0
age                         0
weight                      0
admission_type_id           0
discharge_disposition_id    0
admission_source_id         0
time_in_hospital            0
payer_code                  0
medical_specialty           0
num_lab_procedures          0
num_procedures              0
num_medications             0
number_outpatient           0
number_emergency            0
number_inpatient            0
diag_1                      0
diag_2                      0
diag_3                      0
number_diagnoses            1
metformin                   1
repaglinide                 1
nateglinide                 1
chlorpropamide              1
glimepiride                 1
acetohexamide               1
glipizide                   1
glyburide                   1
tolbutamide                 1
pioglitazone                1
rosiglitazone               1
acarbose                    1
miglitol                    1
troglitazone                1
tolazamide                  1
examide                     1
citoglipton                 1
insulin                     1
glyburide-metformin         1
glipizide-metformin         1
glimepiride-pioglitazone    1
metformin-rosiglitazone     1
metformin-pioglitazone      1
change                      1
diabetesMed                 1
readmitted                  1
dtype: int64

In [11]:
cols = [
    'metformin','repaglinide','nateglinide','chlorpropamide',
    'glimepiride','acetohexamide','glipizide','glyburide',
    'tolbutamide','pioglitazone','rosiglitazone','acarbose',
    'miglitol','troglitazone','tolazamide','examide',
    'citoglipton','insulin','glyburide-metformin',
    'glipizide-metformin','glimepiride-pioglitazone',
    'metformin-rosiglitazone','metformin-pioglitazone',
    'change','diabetesMed'
]

for col in cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_451/1265517050.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [12]:
df['number_diagnoses'].describe()

count    27792.000000
mean         6.826641
std          2.037456
min          1.000000
25%          5.000000
50%          7.000000
75%          9.000000
max          9.000000
Name: number_diagnoses, dtype: float64

In [13]:
df["number_diagnoses"] = df["number_diagnoses"].fillna(df["number_diagnoses"].mean())

In [14]:
df.head()

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [15]:
df['weight'].unique()

array(['?', '[75-100)', '[50-75)', '[0-25)', '[100-125)', '[25-50)',
       '[125-150)', '[175-200)', '[150-175)', '>200'], dtype=object)

In [16]:
df['race'].unique()

array(['Caucasian', 'AfricanAmerican', '?', 'Other', 'Asian', 'Hispanic'],
      dtype=object)

In [17]:
df = df.drop(['encounter_id','patient_nbr','weight'], axis=1, errors='ignore')

In [18]:
df.duplicated().sum()

np.int64(0)

In [19]:
df.replace('?', np.nan, inplace=True)

In [20]:
df.head()

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,Caucasian,Female,[0-10),6,25,1,1,NaN,Pediatrics-Endocrinology,41,...,No,No,No,No,No,No,No,No,No,NO
1,Caucasian,Female,[10-20),1,1,7,3,NaN,NaN,59,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,AfricanAmerican,Female,[20-30),1,1,7,2,NaN,NaN,11,...,No,No,No,No,No,No,No,No,Yes,NO
3,Caucasian,Male,[30-40),1,1,7,2,NaN,NaN,44,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,Caucasian,Male,[40-50),1,1,7,1,NaN,NaN,51,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [21]:
missing_percentage = (df.isnull().sum() / len(df)) * 100
print(missing_percentage)

race                         1.781024
gender                       0.000000
age                          0.000000
admission_type_id            0.000000
discharge_disposition_id     0.000000
admission_source_id          0.000000
time_in_hospital             0.000000
payer_code                  94.066851
medical_specialty           39.402008
num_lab_procedures           0.000000
num_procedures               0.000000
num_medications              0.000000
number_outpatient            0.000000
number_emergency             0.000000
number_inpatient             0.000000
diag_1                       0.028784
diag_2                       0.572086
diag_3                       2.543806
number_diagnoses             0.000000
metformin                    0.000000
repaglinide                  0.000000
nateglinide                  0.000000
chlorpropamide               0.000000
glimepiride                  0.000000
acetohexamide                0.000000
glipizide                    0.000000
glyburide                    0.000000
tolbutamide                  0.000000
pioglitazone                 0.000000
rosiglitazone                0.000000
acarbose                     0.000000
miglitol                     0.000000
troglitazone                 0.000000
tolazamide                   0.000000
examide                      0.000000
citoglipton                  0.000000
insulin                      0.000000
glyburide-metformin          0.000000
glipizide-metformin          0.000000
glimepiride-pioglitazone     0.000000
metformin-rosiglitazone      0.000000
metformin-pioglitazone       0.000000
change                       0.000000
diabetesMed                  0.000000
readmitted                   0.003598
dtype: float64

In [22]:
df.isnull().sum()

race                          495
gender                          0
age                             0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  26144
medical_specialty           10951
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          8
diag_2                        159
diag_3                        707
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      1
dtype: int64

In [23]:
df['race'] = df['race'].fillna(df['race'].mode()[0])

In [24]:
df['readmitted'].unique()

array(['NO', '>30', '<30', None], dtype=object)

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27793 entries, 0 to 27792
Data columns (total 45 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   race                      27793 non-null  object
 1   gender                    27793 non-null  object
 2   age                       27793 non-null  object
 3   admission_type_id         27793 non-null  int64
 4   discharge_disposition_id  27793 non-null  int64
 5   admission_source_id       27793 non-null  int64
 6   time_in_hospital          27793 non-null  int64
 7   payer_code                1649 non-null   object
 8   medical_specialty         16842 non-null  object
 9   num_lab_procedures        27793 non-null  int64
 10  num_procedures            27793 non-null  int64
 11  num_medications           27793 non-null  int64
 12  number_outpatient         27793 non-null  int64
 13  number_emergency          27793 non-null  int64
 14  number_inpatient          27793 non-null  int64
 15  diag_1                    27785 non-null  object
 16  diag_2                    27634 non-null  object
 17  diag_3                    27086 non-null  object
 18  number_diagnoses          27793 non-null  float64
 19  metformin                 27793 non-null  object
 20  repaglinide               27793 non-null  object
 21  nateglinide               27793 non-null  object
 22  chlorpropamide            27793 non-null  object
 23  glimepiride               27793 non-null  object
 24  acetohexamide             27793 non-null  object
 25  glipizide                 27793 non-null  object
 26  glyburide                 27793 non-null  object
 27  tolbutamide               27793 non-null  object
 28  pioglitazone              27793 non-null  object
 29  rosiglitazone             27793 non-null  object
 30  acarbose                  27793 non-null  object
 31  miglitol                  27793 non-null  object
 32  troglitazone              27793 non-null  object
 33  tolazamide                27793 non-null  object
 34  examide                   27793 non-null  object
 35  citoglipton               27793 non-null  object
 36  insulin                   27793 non-null  object
 37  glyburide-metformin       27793 non-null  object
 38  glipizide-metformin       27793 non-null  object
 39  glimepiride-pioglitazone  27793 non-null  object
 40  metformin-rosiglitazone   27793 non-null  object
 41  metformin-pioglitazone    27793 non-null  object
 42  change                    27793 non-null  object
 43  diabetesMed               27793 non-null  object
 44  readmitted                27792 non-null  object
dtypes: float64(1), int64(10), object(34)
memory usage: 9.5+ MB

In [26]:
gender_map = {"Male":0,"Female":1}
df["gender"] = df["gender"].map(gender_map)

In [27]:
age_map = {
    '[0-10)':0,
    '[10-20)':1,
    '[20-30)':2,
    '[30-40)':3,
    '[40-50)':4,
    '[50-60)':5,
    '[60-70)':6,
    '[70-80)':7,
    '[80-90)':8,
    '[90-100)':9
}

df["age"] = df["age"].map(age_map)

In [28]:
readmitted_map={'NO':0,'>30':1,'<30':1} # Map both '>30' and '<30' to 1
df["readmitted"] = df["readmitted"].map(readmitted_map)

In [29]:
df.head()

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,Caucasian,1,0,6,25,1,1,NaN,Pediatrics-Endocrinology,41,...,No,No,No,No,No,No,No,No,No,0.0
1,Caucasian,1,1,1,1,7,3,NaN,NaN,59,...,No,Up,No,No,No,No,No,Ch,Yes,1.0
2,AfricanAmerican,1,2,1,1,7,2,NaN,NaN,11,...,No,No,No,No,No,No,No,No,Yes,0.0
3,Caucasian,0,3,1,1,7,2,NaN,NaN,44,...,No,Up,No,No,No,No,No,Ch,Yes,0.0
4,Caucasian,0,4,1,1,7,1,NaN,NaN,51,...,No,Steady,No,No,No,No,No,Ch,Yes,0.0

In [30]:
pd.set_option('display.max_columns',None)

In [31]:
df.isnull().sum()

race                            0
gender                          0
age                             0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  26144
medical_specialty           10951
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          8
diag_2                        159
diag_3                        707
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      1
dtype: int64

In [32]:
df.isnull().sum()

race                            0
gender                          0
age                             0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                  26144
medical_specialty           10951
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          8
diag_2                        159
diag_3                        707
number_diagnoses                0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      1
dtype: int64

In [33]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

# Reload the dataframe to ensure a clean start and prevent it from being empty
df = pd.read_csv("/content/diabetic_data.csv", engine='python', on_bad_lines='skip')

# Drop columns with high NaN values or identifiers
df = df.drop(['encounter_id', 'patient_nbr', 'weight', 'max_glu_serum', 'A1Cresult'], axis=1, errors='ignore')

# Replace '?' with NaN across the DataFrame
df.replace('?', np.nan, inplace=True)

# Drop columns with very high missing percentages
df.drop(['payer_code', 'medical_specialty'], axis=1, inplace=True)

# Fill remaining missing values for categorical features with their mode
df['race'].fillna(df['race'].mode()[0], inplace=True)
df['diag_1'].fillna(df['diag_1'].mode()[0], inplace=True)
df['diag_2'].fillna(df['diag_2'].mode()[0], inplace=True)
df['diag_3'].fillna(df['diag_3'].mode()[0], inplace=True)

# Apply mappings for gender, age, and readmitted status
gender_map = {"Male":0, "Female":1}
df["gender"] = df["gender"].map(gender_map)

age_map = {
    '[0-10)':0, '[10-20)':1, '[20-30)':2, '[30-40)':3, '[40-50)':4,
    '[50-60)':5, '[60-70)':6, '[70-80)':7, '[80-90)':8, '[90-100)':9
}
df["age"] = df["age"].map(age_map)

readmitted_map={'NO':0, '>30':1, '<30':1}
df["readmitted"] = df["readmitted"].map(readmitted_map)

# Fill potential NaNs in 'gender' that might have been introduced if 'Unknown/Invalid' values existed
df['gender'].fillna(df['gender'].mode()[0], inplace=True)

# Define X (features) and y (target)
X = df.drop('readmitted', axis=1)
y = df['readmitted']

# Perform train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

/tmp/ipykernel_451/4238315512.py:18: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['race'].fillna(df['race'].mode()[0], inplace=True)
/tmp/ipykernel_451/4238315512.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['diag_1'].fillna(df['diag_1'].mode()[0], inplace=True)
/tmp/ipykernel_451/4238315512.py:20: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['diag_2'].fillna(df['diag_2'].mode()[0], inplace=True)
/tmp/ipykernel_451/4238315512.py:21: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['diag_3'].fillna(df['diag_3'].mode()[0], inplace=True)
/tmp/ipykernel_451/4238315512.py:37: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gender'].fillna(df['gender'].mode()[0], inplace=True)

In [34]:
import sys
!{sys.executable} -m pip install catboost
from catboost import CatBoostClassifier

model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=8,
    random_state=42,
    verbose=0
)

Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)
Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)
Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)

In [35]:
X=df.drop('readmitted',axis=1)
y=df['readmitted']

In [47]:
# Check for and handle NaN values in y_train before fitting
nan_y_train_indices = y_train[y_train.isnull()].index
if not nan_y_train_indices.empty:
    X_train = X_train.drop(nan_y_train_indices)
    y_train = y_train.drop(nan_y_train_indices)

categorical_features_indices = X_train.select_dtypes(include='object').columns.tolist()
model.fit(X_train, y_train, cat_features=categorical_features_indices)

CatBoostClassifier(depth=8, iterations=500, learning_rate=0.05, random_state=42, verbose=0)

In [49]:
model.score(X_test,y_test)

np.float64(0.655873358517719)

In [52]:
import pandas as pd

# Define the expected columns from X_train (derived from LPpL6ju_uk_O)
# This list must exactly match the columns and their order in X_train used for model training.
expected_columns = ['race', 'gender', 'age', 'admission_type_id', 'discharge_disposition_id',
                    'admission_source_id', 'time_in_hospital', 'num_lab_procedures',
                    'num_procedures', 'num_medications', 'number_outpatient',
                    'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3',
                    'number_diagnoses', 'metformin', 'repaglinide', 'nateglinide',
                    'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide',
                    'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose',
                    'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton',
                    'insulin', 'glyburide-metformin', 'glipizide-metformin',
                    'glimepiride-pioglitazone', 'metformin-rosiglitazone',
                    'metformin-pioglitazone', 'change', 'diabetesMed']

user_data = {
    "race": ["Caucasian"],
    "gender": [1],
    "age": [7],
    "admission_type_id": [1],
    "discharge_disposition_id": [1],
    "admission_source_id": [7],
    "time_in_hospital": [5],
    "num_lab_procedures": [45],
    "num_procedures": [1],
    "num_medications": [15],
    "number_outpatient": [0],
    "number_emergency": [1],
    "number_inpatient": [2],
    "diag_1": ["120"],
    "diag_2": ["85"],
    "diag_3": ["210"],
    "number_diagnoses": [8],
    "metformin": ["Steady"],
    "repaglinide": ["No"],
    "nateglinide": ["No"],
    "chlorpropamide": ["No"],
    "glimepiride": ["Steady"],
    "acetohexamide": ["No"],
    "glipizide": ["No"],
    "glyburide": ["No"],
    "tolbutamide": ["No"],
    "pioglitazone": ["No"],
    "rosiglitazone": ["No"],
    "acarbose": ["No"],
    "miglitol": ["No"],
    "troglitazone": ["No"],
    "tolazamide": ["No"],
    "examide": ["No"],
    "citoglipton": ["No"],
    "insulin": ["Steady"],
    "glyburide-metformin": ["yes"],
    "glipizide-metformin": ["yes"],
    "glimepiride-pioglitazone": ["yes"],
    "metformin-rosiglitazone": ["yes"],
    "metformin-pioglitazone": ["yes"],
    "change": ["Ch"],
    "diabetesMed": ["No"]
}

# Create a DataFrame from user_data
user_df = pd.DataFrame(user_data)

# Reindex user_df to match the order and presence of columns in X_train
# This will drop any columns not in expected_columns and add missing ones with NaN (which then need to be handled).
# Ensure that all expected_columns are present in user_data to avoid NaN introduction for critical features.
user_df = user_df[expected_columns]

# Ensure dtypes for categorical features match training data
# This assumes `categorical_features_indices` is available from a previous cell
# and that the model was trained with string categories.
for col in categorical_features_indices:
    if col in user_df.columns and not pd.api.types.is_object_dtype(user_df[col]):
        user_df[col] = user_df[col].astype(str)

prediction = model.predict(user_df)

if prediction[0] == 1:
    print("⚠️ Patient is likely to be Readmitted.")
else:
    print("✅ Patient is not likely to be Readmitted.")

⚠️ Patient is likely to be Readmitted.

In [42]:
import pickle
from catboost import CatBoostClassifier

# Re-initialize and train the model (assuming X_train, y_train, categorical_features_indices are available from previous cells)
# In a real scenario, you would run the preceding cells to define these.
# For the purpose of fixing this error, we'll assume the setup for these variables is correct
# and just ensure the model itself is instantiated and fitted.

# Define the CatBoostClassifier model (as in cell OKucy46uui6m)
model = CatBoostClassifier(
    iterations=500,
    learning_rate=0.05,
    depth=8,
    random_state=42,
    verbose=0
)

# Fit the model (as in cell Z8fnikaSwOp6)
# Note: X_train, y_train, and categorical_features_indices must be defined from previous cells
# If these are not defined, the error will shift to those variables.
# Ensure all preceding cells are run.

# Placeholder for X_train, y_train, categorical_features_indices if not defined in current session
# In a real execution flow, these would come from previous cells like LPpL6ju_uk_O
# and Z8fnikaSwOp6.
# For this fix, we assume they are either in scope or would be provided by running previous cells.
# If you're running this cell in isolation after a kernel restart, you would need to run the full pipeline.

# As per the notebook state, X_train, y_train, and categorical_features_indices are defined in cell LPpL6ju_uk_O and Z8fnikaSwOp6.
# Therefore, we just need to re-run those cells or ensure they've been run.
# For the purpose of making this cell runnable independently if the kernel resets,
# we should include the necessary definitions if they don't persist.

# For simplicity and assuming previous cells were run, we'll just re-initialize and fit here.
# However, the best practice is to run all dependent cells.

# This code assumes X_train, y_train, and categorical_features_indices are already in the global scope
# if the user ran the previous cells. If not, this cell alone will not fully resolve dependencies.

# Re-fitting the model
# Assuming `X_train`, `y_train` and `categorical_features_indices` are available from previous runs
# If not, the user must run cells LPpL6ju_uk_O and Z8fnikaSwOp6 first.
# To make this code runnable in isolation for demonstration:
# from sklearn.model_selection import train_test_split
# X = pd.DataFrame(np.random.rand(100, 10), columns=[f'feature_{i}' for i in range(10)])
# X['categorical_feature'] = np.random.choice(['A', 'B', 'C'], 100)
# y = pd.Series(np.random.randint(0, 2, 100))
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# categorical_features_indices = X_train.select_dtypes(include='object').columns.tolist()

model.fit(X_train, y_train, cat_features=categorical_features_indices)

pickle.dump(model, open("house_price_model.pkl", "wb"))